from bs4 import BeautifulSoup
import requests

url = "https://www.dolarhoy.com/"
page = requests.get(url)
soup = BeautifulSoup(page.content, "html.parser")

col6 = soup.find_all("div", class_="col-6")
precioDeCompraOficial = col6[0].find_all("span")
precioDeVentaOficial = col6[1].find_all("span")
precioDeCompraBlue = col6[2].find_all("span")
precioDeVentaBlue = col6[3].find_all("span")
precioDeCompraBolsa = col6[4].find_all("span")
precioDeVentaBolsa = col6[5].find_all("span")
precioDeCompraLiqui = col6[6].find_all("span")
precioDeVentaLiqui = col6[7].find_all("span")
precioDeCompraTurista = col6[8].find_all("span")
precioDeVentaTurista = col6[9].find_all("span")

print("$$$$$$$$$$ Dolar Oficial $$$$$$$$$$$$")
print("_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_")
print("Precio de compra: "+precioDeCompraOficial[0].text)
print("-----------------------------------------")
print("Precio de venta: "+precioDeVentaOficial[0].text)
print("_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_")
print("$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$")
print("")

print("$$$$$$$$$$ Dolar Blue $$$$$$$$$$$$")
print("_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_")
print("Precio de compra: "+precioDeCompraBlue[0].text)
print("-----------------------------------------")
print("Precio de venta: "+precioDeVentaBlue[0].text)
print("_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_")
print("$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$")
print("")

print("$$$$$$$$$$ Dolar Bolsa $$$$$$$$$$$$")
print("_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_")
print("Precio de compra: "+precioDeCompraBolsa[0].text)
print("-----------------------------------------")
print("Precio de venta: "+precioDeVentaBolsa[0].text)
print("_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_")
print("$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$")
print("")

print("$$$$$$$$$$ Dolar contado con liqui $$$$$$$$$$$$")
print("_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_")
print("Precio de compra: "+precioDeCompraLiqui[0].text)
print("-----------------------------------------")
print("Precio de venta: "+precioDeVentaLiqui[0].text)
print("_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_")
print("$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$")
print("")

print("$$$$$$$$$$ Dolar Turista $$$$$$$$$$$$")
print("_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_")
print("Precio de compra: "+precioDeCompraTurista[0].text)
print("-----------------------------------------")
print("Precio de venta: "+precioDeVentaTurista[0].text)
print("_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_")
print("$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$")
print("")